# Generated by Django 6.0.4 on 2026-04-25 02:50
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
class Migration(migrations.Migration):
    initial = True
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
    operations = [
        migrations.CreateModel(
            name='CachedManga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mangadex_id', models.CharField(db_index=True, max_length=36, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('alt_titles', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('author', models.CharField(blank=True, max_length=300)),
                ('artist', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(blank=True, choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('hiatus', 'Hiatus'), ('cancelled', 'Cancelled')], max_length=20)),
                ('cover_url', models.URLField(blank=True, max_length=1000)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('content_rating', models.CharField(blank=True, max_length=30)),
                ('last_chapter', models.CharField(blank=True, max_length=20)),
                ('follow_count', models.IntegerField(default=0)),
                ('cached_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-cached_at'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('mangadex_id', models.CharField(db_index=True, max_length=36, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CachedChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mangadex_id', models.CharField(db_index=True, max_length=36, unique=True)),
                ('chapter_number', models.CharField(blank=True, max_length=20)),
                ('volume', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('language', models.CharField(default='en', max_length=10)),
                ('pages_count', models.IntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('scanlation_group', models.CharField(blank=True, max_length=300)),
                ('cached_at', models.DateTimeField(auto_now=True)),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='manga.cachedmanga')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_type', models.CharField(choices=[('reading', 'Reading'), ('plan_to_read', 'Plan to Read'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('dropped', 'Dropped')], default='reading', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='manga.cachedmanga')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='cachedmanga',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='manga', to='manga.genre'),
        ),
        migrations.CreateModel(
            name='ReadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_by', to='manga.cachedchapter')),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_history', to='manga.cachedmanga')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-read_at'],
            },
        ),
        migrations.AddIndex(
            model_name='cachedchapter',
            index=models.Index(fields=['manga', 'language'], name='manga_cache_manga_i_df6f14_idx'),
        ),
        migrations.AddIndex(
            model_name='cachedchapter',
            index=models.Index(fields=['published_at'], name='manga_cache_publish_50e46c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('user', 'manga')},
        ),
        migrations.AddIndex(
            model_name='cachedmanga',
            index=models.Index(fields=['mangadex_id'], name='manga_cache_mangade_073f87_idx'),
        ),
        migrations.AddIndex(
            model_name='cachedmanga',
            index=models.Index(fields=['status'], name='manga_cache_status_fb04d6_idx'),
        ),
        migrations.AddIndex(
            model_name='cachedmanga',
            index=models.Index(fields=['cached_at'], name='manga_cache_cached__44ee04_idx'),
        ),
        migrations.AddIndex(
            model_name='cachedmanga',
            index=models.Index(fields=['follow_count'], name='manga_cache_follow__b518af_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='readhistory',
            unique_together={('user', 'chapter')},
        ),
    ]
