# Generated by Django 6.0.4 on 2026-04-25 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cachedmanga',
            name='manga_cache_mangade_073f87_idx',
        ),
    ]
