# Generated by Django 6.0.4 on 2026-04-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0002_remove_cachedmanga_manga_cache_mangade_073f87_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedmanga',
            name='custom_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
