# Generated by Django 6.0.4 on 2026-04-26 13:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0003_cachedmanga_custom_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='readhistory',
            unique_together={('user', 'manga')},
        ),
    ]
